# Generated by Django 3.1.1 on 2020-12-30 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_gallery_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employees',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
